### ISSUE TITLE
Использование относительных ссылок

### ISSUE THREAD

**Issue by lex111** [natenka/pyneng-book#12]
То есть вместо такого 
```rst
Созданию функций посвящён `девятый
раздел <https://pyneng.readthedocs.io/ru/latest/book/09_functions/index.html>`__.
```

Будет так

```rst
Созданию функций посвящён `девятый
раздел :ref:`functions_index`.
```

[Документация](http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-ref)

@natenka как идея?

**Comment by natenka** [comment]
Идея очень правильная. Спасибо!
У меня никак руки не доходили разобраться со ссылками. Заменила ссылки на разделы на относительные.

**Comment by lex111** [comment]
В этом [пулреквесте](https://github.com/natenka/pyneng-book/pull/14) заменил остальные ссылки.
