### ISSUE TITLE
Ресурсы для обучения по книге

### ISSUE THREAD

**Issue by krote5k** [natenka/pyneng-book#21]
На 11 странице неверная ссылка на [вопросы мини-задания](https://github.com/natenka/pyneng-examples-exercises/blob/master/tests.md), верная думаю всё же https://github.com/natenka/pyneng-examples-exercises/tree/master/tests

**Comment by pyneng** [comment]
Спасибо! Исправила

**Comment by natenka** [comment]
Спасибо! Исправила
