### ISSUE TITLE
Epub: Обложка

### ISSUE THREAD

**Issue by Sergey371** [natenka/pyneng-book#29]
При чтении Epub формата на электронной книжке (замечено на Kindle Oasis 10-е поколение, прошивка Kindle 5.15.1) в списке личной библиотеки книга  "Python для сетевых инженеров" отображается с нечитаемой мутной (не резкой) картинкой вместо обложки из-за чего невозможно понять что за книга
![IMG_20230203_122011](https://user-images.githubusercontent.com/65397484/216576286-aaeb6568-2bc8-46d3-b500-9d46501cb094.jpg)
.
Epub файл получен с официального сайта через меню скачать Epub файл).

**Comment by Sergey371** [comment]
Вероятно проблема заключается в том что в качестве обложки используется некий (первый, случайный) рисунок из книги и неудачно масштабируется. В качестве решения предлагаю задавать явно смакетированную обложку через опцию epub_cover в файле конфигурации  conf.py.

**Comment by natenka** [comment]
Можно проверять. Вроде и содержание и обложка исправлены

**Comment by Sergey371** [comment]
Большое спасибо! И обложка и содержание исправлены, проверено, подтверждаю.
