### ISSUE TITLE
Epub: Содержание только из одного пункта

### ISSUE THREAD

**Issue by Sergey371** [natenka/pyneng-book#30]
При чтении Epub формата на электронной книжке (замечено на Kindle Oasis 10-е поколение, прошивка Kindle 5.15.1) содержание состоит только из одного пункта "Python для сетевых инженеров 2
![IMG_20230203_121953](https://user-images.githubusercontent.com/65397484/216576341-614a04d7-0b3f-4fb4-aa56-f9c26a6862e4.jpg)
" и больше ни каких других глав.
Epub файл получен с официального сайта через меню скачать Epub файл).

**Comment by natenka** [comment]
Можно проверять. Содержание и обложка исправлены

**Comment by Sergey371** [comment]
Большое спасибо! И обложка и содержание исправлены, проверено, подтверждаю.
